# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# compile C with /usr/bin/cc
# compile CUDA with /usr/local/cuda/bin/nvcc
# compile CXX with /usr/bin/c++
C_FLAGS = -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -Wno-deprecated-declarations -Wno-write-strings  -Ofast -DNDEBUG -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -fPIC   -fopenmp

C_DEFINES = -DCUDNN -DCUDNN_HALF -DGPU -DLIB_EXPORTS=1 -DOPENCV -DUSE_CMAKE_LIBS -Ddark_EXPORTS

C_INCLUDES = -I/content/drive/MyDrive/ICIS_Paper/darknet/include -I/content/drive/MyDrive/ICIS_Paper/darknet/src -I/content/drive/MyDrive/ICIS_Paper/darknet/3rdparty/stb/include -I/usr/local/cuda/targets/x86_64-linux/include -isystem /usr/include/opencv 

CUDA_FLAGS = -gencode arch=compute_75,code=sm_75 --compiler-options " -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -Wno-deprecated-declarations -Wno-write-strings -DGPU -DCUDNN -DOPENCV -fPIC -fopenmp -Ofast "  -O3 -DNDEBUG -Xcompiler=-fPIC  

CUDA_DEFINES = -DCUDNN -DCUDNN_HALF -DGPU -DLIB_EXPORTS=1 -DOPENCV -DUSE_CMAKE_LIBS -Ddark_EXPORTS

CUDA_INCLUDES = -I/content/drive/MyDrive/ICIS_Paper/darknet/include -I/content/drive/MyDrive/ICIS_Paper/darknet/src -I/content/drive/MyDrive/ICIS_Paper/darknet/3rdparty/stb/include -I/usr/local/cuda/targets/x86_64-linux/include -isystem=/usr/include/opencv 

CXX_FLAGS = -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -Wno-deprecated-declarations -Wno-write-strings  -Ofast -DNDEBUG -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -fPIC -fvisibility=hidden   -fopenmp -std=gnu++11

CXX_DEFINES = -DCUDNN -DCUDNN_HALF -DGPU -DLIB_EXPORTS=1 -DOPENCV -DUSE_CMAKE_LIBS -Ddark_EXPORTS

CXX_INCLUDES = -I/content/drive/MyDrive/ICIS_Paper/darknet/include -I/content/drive/MyDrive/ICIS_Paper/darknet/src -I/content/drive/MyDrive/ICIS_Paper/darknet/3rdparty/stb/include -I/usr/local/cuda/targets/x86_64-linux/include -isystem /usr/include/opencv 

