# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# The generator used is:
set(CMAKE_DEPENDS_GENERATOR "Unix Makefiles")

# The top level Makefile was generated from the following files:
set(CMAKE_MAKEFILE_DEPENDS
  "CMakeCache.txt"
  "../CMakeLists.txt"
  "../DarknetConfig.cmake.in"
  "CMakeFiles/3.12.0/CMakeCCompiler.cmake"
  "CMakeFiles/3.12.0/CMakeCUDACompiler.cmake"
  "CMakeFiles/3.12.0/CMakeCXXCompiler.cmake"
  "CMakeFiles/3.12.0/CMakeSystem.cmake"
  "detect_cuda_compute_capabilities.cu"
  "../cmake/Modules/FindCUDNN.cmake"
  "../cmake/Modules/FindStb.cmake"
  "../src/version.h.in"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/BasicConfigVersion-SameMajorVersion.cmake.in"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeCInformation.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeCUDAInformation.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeCXXInformation.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeCommonLanguageInclude.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeGenericSystem.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeInitializeConfigs.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeLanguageInformation.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakePackageConfigHelpers.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeParseImplicitLinkInfo.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeSystemSpecificInformation.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CMakeSystemSpecificInitialize.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CheckIncludeFile.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CheckLanguage.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CheckLibraryExists.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/CheckSymbolExists.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Compiler/CMakeCommonCompilerMacros.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Compiler/GNU-C.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Compiler/GNU-CXX.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Compiler/GNU.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Compiler/NVIDIA-CUDA.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindCUDA.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindCUDA/select_compute_arch.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindOpenMP.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageMessage.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindThreads.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Platform/Linux-GNU-C.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Platform/Linux-GNU-CXX.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Platform/Linux-GNU.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Platform/Linux.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/Platform/UnixPaths.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/SelectLibraryConfigurations.cmake"
  "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/WriteBasicConfigVersionFile.cmake"
  "/usr/share/OpenCV/OpenCVConfig-version.cmake"
  "/usr/share/OpenCV/OpenCVConfig.cmake"
  "/usr/share/OpenCV/OpenCVModules-release.cmake"
  "/usr/share/OpenCV/OpenCVModules.cmake"
  )

# The corresponding makefile is:
set(CMAKE_MAKEFILE_OUTPUTS
  "Makefile"
  "CMakeFiles/cmake.check_cache"
  )

# Byproducts of CMake generate step:
set(CMAKE_MAKEFILE_PRODUCTS
  "../src/version.h"
  "DarknetConfig.cmake"
  "CMakeFiles/DarknetConfig.cmake"
  "DarknetConfigVersion.cmake"
  "CMakeFiles/CMakeDirectoryInformation.cmake"
  )

# Dependency information for all targets:
set(CMAKE_DEPEND_INFO_FILES
  "CMakeFiles/darknet.dir/DependInfo.cmake"
  "CMakeFiles/uselib.dir/DependInfo.cmake"
  "CMakeFiles/dark.dir/DependInfo.cmake"
  )
